/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EmergencyGuideIndexRouteImport } from './routes/emergency-guide/index'
import { Route as EmergencyGuideSlugRouteImport } from './routes/emergency-guide/$slug'

const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyGuideIndexRoute = EmergencyGuideIndexRouteImport.update({
  id: '/emergency-guide/',
  path: '/emergency-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyGuideSlugRoute = EmergencyGuideSlugRouteImport.update({
  id: '/emergency-guide/$slug',
  path: '/emergency-guide/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/emergency-guide/$slug': typeof EmergencyGuideSlugRoute
  '/emergency-guide/': typeof EmergencyGuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/emergency-guide/$slug': typeof EmergencyGuideSlugRoute
  '/emergency-guide': typeof EmergencyGuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/features': typeof FeaturesRoute
  '/emergency-guide/$slug': typeof EmergencyGuideSlugRoute
  '/emergency-guide/': typeof EmergencyGuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/emergency-guide/$slug'
    | '/emergency-guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/emergency-guide/$slug'
    | '/emergency-guide'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/features'
    | '/emergency-guide/$slug'
    | '/emergency-guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FeaturesRoute: typeof FeaturesRoute
  EmergencyGuideSlugRoute: typeof EmergencyGuideSlugRoute
  EmergencyGuideIndexRoute: typeof EmergencyGuideIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-guide/': {
      id: '/emergency-guide/'
      path: '/emergency-guide'
      fullPath: '/emergency-guide/'
      preLoaderRoute: typeof EmergencyGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency-guide/$slug': {
      id: '/emergency-guide/$slug'
      path: '/emergency-guide/$slug'
      fullPath: '/emergency-guide/$slug'
      preLoaderRoute: typeof EmergencyGuideSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FeaturesRoute: FeaturesRoute,
  EmergencyGuideSlugRoute: EmergencyGuideSlugRoute,
  EmergencyGuideIndexRoute: EmergencyGuideIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
